//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _27_DoDinhTuan_21103100756_DHTI15A1CL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Diem
    {
        [Key,Column(Order =0)]
        [Required]
        [DisplayName("Mã sinh viên")]
        public int masv { get; set; }
        [Key, Column(Order = 1)]
        [Required]
        [DisplayName("Tên môn học")]
        public string tenmh { get; set; }
        [Required]
        [Range(0,10)]
        [DisplayName("Điểm")]
        public Nullable<double> diem1 { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
    }
}
