//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _27_DoDinhTuan_21103100756_DHTI15A1CL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.Diems = new HashSet<Diem>();
        }
        [Key]
        [DisplayName("Mã sinh viên")]
        public int masv { get; set; }
        [DisplayName("Họ tên")]
        [Required]
        public string hoten { get; set; }
        [Required]
        [DisplayName("Năm sinh")]
        [Range(2000,2006)]
        public Nullable<int> namsinh { get; set; }
        [Required]
        [DisplayName("Giới tính")]
        public string gioitinh { get; set; }
        [Required]
        [EmailAddress]
        [DisplayName("Email")]
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diem> Diems { get; set; }
    }
}
