//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _27_LTUDDN_DoDinhTuan_21103100756.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.PhieuDatBaos = new HashSet<PhieuDatBao>();
        }
        [Key]
        [DisplayName("Mã khách hàng")]
        public int makh { get; set; }
        [Required]
        [StringLength(30, MinimumLength =2)]
        [DisplayName("Tên khách hàng")]
        public string tenkh { get; set; }
        [DisplayName("Địa chỉ")]
        [Required]
        public string diachi { get; set; }
        [DisplayName("Giới tính")]
        [Required]
        public Nullable<bool> gioitinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDatBao> PhieuDatBaos { get; set; }
    }
}
