//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _27_LTUDDN_DoDinhTuan_21103100756.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PhieuDatBao
    {
        [Key, Column(Order = 0)]
        [DisplayName("Tên báo")]
        public string tenbao { get; set; }
        [Key, Column(Order = 1)]
        [DisplayName("Mã khách hàng")]
        public int makh { get; set; }
        [DisplayName("Ngày đặt")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ngaydat { get; set; }
        [Range(1, 100)]
        [DisplayName("Số lượng")]
        public Nullable<int> soluong { get; set; }
        [DisplayName("Đơn giá")]
        public Nullable<decimal> dongia { get; set; }
        [DisplayName("Thành tiền")]
        public decimal thanhtien
        {
            get
            {
                return (decimal)(dongia * soluong);
            }

        }

        public virtual KhachHang KhachHang { get; set; }
    }
}
