//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace De33_DDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonDatMon
    {
        public int MaHD { get; set; }
        public Nullable<int> MaMon { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual MonAn MonAn { get; set; }
    }
}
