//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace De32_DDT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class HoaDonBan
    {
        [Key]
        public int MaHD { get; set; }
        [ForeignKey("Sach")]
        public Nullable<int> MaSach { get; set; }
        [ForeignKey("KhachHang")]
        public Nullable<int> MaKH { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayBan { get; set; }
        [Range(0, int.MaxValue)]
        public Nullable<int> SoLuong { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
