//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _15_LTUDDN_DoDinhTuan_21103100756_15.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BacSi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BacSi()
        {
            this.LichHens = new HashSet<LichHen>();
        }
        [Key]
        [Required]
        public int MaBS { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 5)]
        public string TenBS { get; set; }
        [Required]
        public string ChuyenKhoa { get; set; }
        [Required]
        [Range(0, int.MaxValue)]
        public Nullable<int> SoNamKinhNghiem { get; set; }
        [Required]
        public string DienThoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichHen> LichHens { get; set; }
    }
}
