//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _15_LTUDDN_DoDinhTuan_21103100756_15.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BenhNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BenhNhan()
        {
            this.LichHens = new HashSet<LichHen>();
        }
        [Key]
        [Required]
        public int MaBN { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 5)]
        public string HoTenBN { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Required]
        public Nullable<bool> GioiTinh { get; set; }
        [Required]
        [RegularExpression(@"^0[1-9]{1}[0-9]{8}$")]
        public string DienThoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichHen> LichHens { get; set; }
    }
}
