//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _15_LTUDDN_DoDinhTuan_21103100756_15.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LichHen
    {
        [Key]
        [Required]
        public int MaLichHen { get; set; }
        [Required]
        public Nullable<int> MaBN { get; set; }
        [Required]
        public Nullable<int> MaBS { get; set; }
        [Required]
        [DataType(DataType.DateTime)]

        public Nullable<System.DateTime> NgayHen { get; set; }
        [Required]
        public string LyDo { get; set; }
    
        public virtual BacSi BacSi { get; set; }
        public virtual BenhNhan BenhNhan { get; set; }
    }
}
